package com.superbeta.blibberly.home.presentation

enum class HomeScreenState {
    LIVE_USERS_RETRIEVAL_SUCCESS,
    LIVE_USERS_RETRIEVAL_LOADING,
    LIVE_USERS_RETRIEVAL_ERROR,
    LIVE_USERS_EMPTY,
    LIVE_USERS_PROFILE_RETRIEVAL_SUCCESS,
    LIVE_USERS_PROFILE_RETRIEVAL_LOADING,
    LIVE_USERS_PROFILE_RETRIEVAL_ERROR,
}
